python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/flower-painting
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/genre-painting
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/landscape
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/marina
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/nude-painting-nu
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/portrait
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/religious-painting
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/still-life
python style_embedding.py -style_path /media/pawel/DATA/iwisum/images/symbolic-painting
